### ISSUE TITLE
As a contributor to bdp-core I want to have a clean database schema free of all deprecated or server specific elements, to improve maintainability.

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#22]
Example issues (not complete):
- remove "idle_in_transaction_session_timeout" lines (possible version conflicts between PG server versions and psql client version from which a schema dump has been executed)
- remove roles, except bdp_readonly and bdp from schema dumps
- apt install postgresql-9.5-postgis-2.4
- CREATE EXTENSION postgis with schema public;

The goal is that a new schema can easily be tested on localhost, just from a simple pg_dump of a existing production server's schema.

**UPDATE**:
This to-do list is deprecated, see comments below...

**Comment by Piiit** [comment]
@bertolla 
Done, indirectly through the new schema generator tool, which does no longer dump from Postgres, but generates clean scripts directly from Hibernate SchemaGenerator. See the following files in folder /dal/src/main/resources/META-INF/sql/ (development and jsonmetadata branches):
- schema-1.3.6-dump.sql
- schema-1.3.6-modifications.sql
- schema-2.0.0-dump.sql
- schema-2.0.0-modifications.sql

**Comment by bertolla** [comment]
Schema import and schema modification works fine with all tables in 1.3.6.
If as a dev I try to import this dump the schema of the tables and all contents will not be in schema  'intime' anymore. 
@Piiit 
Is that ok? if I do that manually, it works fine 

In 2.0.0(on jsonmetadata branch) executing the scripts works fine but as soon as I try to create schema intime and execute the scripts there only a part of the schema gets created and it strangely fails with some kind of postgis error:
psql:schema-2.0.0-dump.sql:18: ERROR:  type "geometry" does not exist
LINE 1: ...ected boolean default true not null, linegeometry GEOMETRY, ...

**Comment by Piiit** [comment]
@bertolla 
> If as a dev I try to import this dump the schema of the tables and all contents will not be in schema 'intime' anymore.

That is fine, because we want to keep the schema name configurable. You have just to select your schema with `set search_path` and then execute the script. This is, because we want to install several BDPs within a single DB for testing, comparison, ....

> psql:schema-2.0.0-dump.sql:18: ERROR: type "geometry" does not exist
This type is part of the GIS extension of postgres, which you have not installed or located within another schema. For the latter, you can just set the search path to `public, your_intime` to get it working, if you have your GIS extension within the public schema.

I would say, if these two issues were the only ones, we can close this issue. 
OK?

**Comment by bertolla** [comment]
k
