### ISSUE TITLE
StationList DTO

### ISSUE THREAD

**Issue by mwallnoefer** [idm-suedtirol/bdp-core#38]
What is the purpose of `StationList` as a DTO (https://github.com/idm-suedtirol/bdp-core/blob/master/dto/src/main/java/it/bz/idm/bdp/dto/StationList.java)? Couldn't the 3-4 occurrences be substituted directly by `List<StationDto>`?

**Comment by bertolla** [comment]
There was an issue with the serialization of polymorfic objets when using generics, which means the specific implementation of the StationDto did not get serialized correctly. For example a carsharingstationdto got serialized as StationDto instead. I can't really recall the thread where this was discussed, but as soon as we switched to StationList, the problem got solved.

**Comment by mwallnoefer** [comment]
Ah, okay.

**Comment by mwallnoefer** [comment]
I have opened pull request #40 in this regard.
