### ISSUE TITLE
Re-add domain-specific DTO/DAL handling back into data collectors

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#48]
Moved from #28...
- [x] Re-add CarParkingDynamic handling into the data collector
- [x] ~~Re-add CarPooling translations into Station JSON meta data~~ 
not needed since carpooling never went in production and i18n should be rethought

- [x] ~~Re-add TrafficVehicleRecord handling into data collector~~
Data was never exposed through webservices and datacollector is no longer active

**Comment by Piiit** [comment]
@bertolla Maybe you have done this already, please confirm... just to cleanup deprecated issues.

**Comment by ohnewein** [comment]
@Piiit please test. Thanks!

**Comment by Piiit** [comment]
@bertolla @ohnewein 
The only thing that needs to be fixed is the mismatch between "occupied" and "free" data types for parking stations. The DC inserts "free" records, but the WS needs also "occupied"... we need to fix that on one side or the other. I close this issue, since it is a duplicate of https://github.com/idm-suedtirol/bdp-commons/issues/77.
