### ISSUE TITLE
Write a migration SQL script to update schema and move data from v1 to v2

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#49]
Belongs to the EPIC #28

- [x] Create a snapshot of the current production Postgres RDS instance 
- [x] Create the same machine out of that snapshot as it is in production to compare query performance and query result correctness
- [x] Create a script to update schema dumps inside bdp-core/DAL resources automatically
- Write a migration SQL script:
  - [x] Migrate all basic data into the new JSONB and parent fields of Stations
  - [x] Migrate all dynamic data into the new JSONB stations and measurement tables
  - [x] Migrate types and other non-measurement data
  - [x] Move non bdp-core tables into one or more schemas outside intime (postponed to the next release)
- [x] Create a document on what has been done and share it
  - [x] @rcavaliere, checks if everything is right

**Comment by Piiit** [comment]
@rcavaliere @bertolla 
The migration script is ready for discussion. There are still some open points, that I cannot map onto our current models. Elaboration/ElaborationHistory for instance....

- [SQL script v2.0](https://github.com/idm-suedtirol/bdp-core/blob/jsonmetadata/dal/src/main/resources/META-INF/sql/schema-migration-1.1.0-2.0.0.sql)
- [SQL script v2.0 - README](https://github.com/idm-suedtirol/bdp-core/blob/jsonmetadata/dal/src/main/resources/META-INF/sql/schema-migration-1.1.0-2.0.0-README.md)

**Comment by Piiit** [comment]
@rcavaliere 
See https://github.com/idm-suedtirol/bdp-core/blob/jsonmetadata/dal/src/main/resources/META-INF/sql/schema-2.0.0-dump.sql and https://github.com/idm-suedtirol/bdp-core/blob/jsonmetadata/dal/src/main/resources/META-INF/sql/schema-2.0.0-modifications.sql

Please also read https://github.com/idm-suedtirol/bdp-core/blob/jsonmetadata/dal/src/main/resources/META-INF/sql/README.md#files-with-pattern-schema-version-typesql. It explains why we have two files for our schema.

**Comment by Piiit** [comment]
@rcavaliere I think the test is a huge task, so I will write a script that executes the same query on the old and the new API and compares results and runtime. If results are equal and performance similar we are OK. (See #50 and #58)

Is your manual glance to my script and description OK, just to understand that I have understood everything right. If you want we can also have a meeting for ~2 hours to go through everything...

**Comment by rcavaliere** [comment]
@Piiit already replied by voice. OK to proceed like that, next week I will have a deep look at your documentation.
