### ISSUE TITLE
As a maintainer of the BDP, I want to have all queries on our Geoserver compatible with version 2 of bdp-core

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#54]
https://ipchannels.integreen-life.bz.it/geoserver/web/

**Comment by bertolla** [comment]
@rcavaliere 
Are this geoserver layers also to migrate to v2?
- no2_1_microgm3_ma_position
- Congestion
- output_caline_NO2
- output_caline_PM10

**Comment by rcavaliere** [comment]
@bertolla please yes, we are going to reactivate them during the next months

**Comment by Piiit** [comment]
@rcavaliere @bertolla 
I did the following queries now:
- [x] edi:congestion
- [x] edi:pollution_pm10

Which additional queries do you need? Please add to this list here... 

To know what else has been done, check the Geoserver webapp and see which layers exist with a prefix `integreen:V2-`.

**Comment by Piiit** [comment]
@bertolla @rcavaliere I move it to testing... please let me know if something is missing.

**Comment by bertolla** [comment]
Tested it with http://mobilityv2.meran.eu.s3-website-eu-west-1.amazonaws.com/ and the layers there seem to work correctly. which means:

:heavy_check_mark:  parking
:heavy_check_mark:  carsharing
:heavy_check_mark:  emobility

I also checked directly on geoserver:
:heavy_check_mark: carpooling
:heavy_check_mark: bikesharing
:heavy_check_mark: cleanroads_stations

For these layers Roberto C. should give it a look:

- congestion             
- no2_1_microgm3_ma_position 
- pollution_nox
- pollution_pm10

--

**Comment by rcavaliere** [comment]
These additional layers will be reimplemented, so if Geoserver works with the other layers I would close this issue
