### ISSUE TITLE
As a maintainer of the Big Data Platform v2, I want to use all data collectors as in v1

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#58]
Belongs to the EPIC #28 
Datacollectors to mirror which are running on the v1 in production(where the endpoints are still working):
- [x] parking-MeBo
- [x] emoblity
- [x] carsharing
- [x] airquality
- [x] bluetooth
- [x] emobility-hydrogen
- [x] metorology
- [x] parking-tn

New TODO after testing: 
- [x] <strike>Fix parking issues related to data types `occupied` and `free`</strike>
> This is not part of the DC, therefore not relevant for this user story
- [x] <strike>General issues</strike> 
> Not part of this issue, just as reference to a new user story
- [x] Fix carsharing issues
- [x] ~Remove wrong DTO reference from emobility-echarging & emobility-hydrogen~
There is no reference to the dto, but there is some outdated documentation and properties in property file which get not used.

**Comment by ohnewein** [comment]
@Piiit please test. Thanks!

**Comment by Piiit** [comment]
Tests:
- [ ] parking-MeBo
- [ ] emoblity
- [ ] carsharing
- [ ] airquality
- [ ] bluetooth
- [ ] emobility-hydrogen
- [ ] metorology
- [ ] parking-tn

**Comment by Piiit** [comment]
Tests:
- [ ] parking-MeBo
- [ ] emoblity
- [ ] carsharing
- [ ] airquality
- [ ] bluetooth
- [ ] emobility-hydrogen
- [ ] metorology
- [ ] parking-tn

**Comment by Piiit** [comment]
@bertolla Tested... most things are OK, but we have some issues to solve... see comment above.

**Comment by Piiit** [comment]
@bertolla @rcavaliere I think we are done with this, all remaining issue have either a separate user story or are low priority (minor issues) and can be fixed after the migration easier
