### ISSUE TITLE
As a service provider, I would like to get real-time parking and car sharing data as open data (CC0 license)

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/bdp-core#61]
Due to the fact that we go the agreement to publish them with an open data license

**Comment by bertolla** [comment]
The data was always reachable for the simple reason that our client applications did not have any authentication mechanism. For example if we disable parking TN realtime data will stop appearing on parking.bz.it.

**Comment by ohnewein** [comment]
@stefanodavid could you please update license information in the documentation? @rcavaliere will help you figure out the right settings.
