### ISSUE TITLE
Station name gets set only if it is null

### ISSUE THREAD

**Issue by bertolla** [idm-suedtirol/bdp-core#69]
Station name gets set only if it is null, otherwise the old station name get's used. Is this a wanted behaviour or not? Please comment and think of practical cases where it made sense for us to have this logic
- [x] check implications
- [x] rewrite logic

**Comment by bertolla** [comment]
should be solved with 8aec3940cf17f3ead78b2884e218276ff7d56c07

**Comment by ohnewein** [comment]
@Piiit please test

**Comment by Piiit** [comment]
Tested and deployed on production
