### ISSUE TITLE
Missing schema details in v2

### ISSUE THREAD

**Issue by bertolla** [idm-suedtirol/bdp-core#70]
Things which are not working right now on v2:
- [x] missing unique constraint on measurement table(station,type,period)
- [x] missing unique constraint on measurementhistory table(station,type,period,timestamp,value)
- [x] missing unique constraint on measurementstring table(station,type,period)
- [x] missing unique constraint on measurementstringhistory table(station,type,period,timestamp,value)
- [x] missing unique constraint on elaboration table(station,type,period)
- [x] missing unique constraint on elaborationhistory table(station,type,period,timestamp,value)

**UPDATE** We solve this during our migration, because it would have been a lot of work solving it on V1

**Comment by Piiit** [comment]
@bertolla It is not possible to create these uniqueness constraints, it tells me that there are duplicates

**Comment by Piiit** [comment]
@bertolla 
Today nichgt a script will do the following on our test DB for V2 (intimev2dc and intimev2ws):
- eliminate the duplicates inside measurement and measurementstring tables and create an UC for (station,type,period)
- eliminate the duplicates inside measurementhistory and measurementstringhistory tables and create an UC for (station,type,period,timestamp,value)

**Comment by Piiit** [comment]
FYI, the query is:
```
DELETE FROM intimev2ws.measurementhistory a USING intimev2ws.measurementhistory b
WHERE
    a.id < b.id
    AND a.station_id = b.station_id AND a.type_id = b.type_id AND a.period = b.period AND a.timestamp = b.timestamp AND a.double_value = b.double_value;
```

**Comment by Piiit** [comment]
@bertolla Please test

**Comment by Piiit** [comment]
It did not work for the intimev2dc schema, because data  collectors are writing on it... so we managed to delete 2636121 duplicates, but before we could create the unique constraint, some data collectors inserted new duplicates.

**Comment by Piiit** [comment]
@bertolla This will be done during migration. We will check if the unique constraint holds afterwards... that should be enough for testing.
