### ISSUE TITLE
The quick build script fails due to errorneous extension loading

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#71]
- [x] Move it from the dump.sql file (see DAL) into quickbuild.sh
- [x] documentation

**Comment by Piiit** [comment]
@bertolla 
Done. Please test... 

See https://github.com/idm-suedtirol/bdp-core/blob/development/README.md#installation-guide

**Comment by bertolla** [comment]
quickbuildscript fails silently and we got some regressions with .dist files.
I put this back in development

**Comment by Piiit** [comment]
@bertolla Fixed. However, the I cannot reproduce the .dist regression.

**Comment by bertolla** [comment]
Script is now working correctly
