### ISSUE TITLE
As a maintainer of the BDP v2, I want to have an easy to use schema creation script, that dumps all Hibernate entities into a schema.sql file

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#72]
- [x] create a schema generator Java application
- [x] Issue: "geometry" columns get created as "bytea"
- [x] create a shell script to execute schema exports from CLI
- [x] update quickbuild.sh to no longer support schema dumps
- [x] write a documentation about this
- [x] update schema-dump-2.0.0.sql with the newest dump
- [x] change the quickbuild script to support different bdp-users and schema names
- [x] backport it to the development branch

**Comment by Piiit** [comment]
@bertolla Done. Please test... See tools/README.md

**Comment by bertolla** [comment]
Accidentaly started with java 11 and it failed. With java 8 it seems to work correctly.
